// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnfvbqpfdksnbqyuanzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZnZicXBmZGtzbmJxeXVhbnpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDE5MjMsImV4cCI6MjA3MTAxNzkyM30.3nUwLJxcopV1OMxKSg3H-aa-3Pqs4ZX2VVr_NMId8dE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});